---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "nymphium"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "nymphium"
