---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions-all:
        patterns:
          - '*'
    schedule:
      interval: "weekly"
    cooldown:
      - default-days: 30
    assignees:
      - "@Nymphium"
  - package-ecosystem: bundler
    directory: "/"
    groups:
      bundler-all:
        patterns:
          - '*'
    schedule:
      interval: "weekly"
    cooldown:
      - default-days: 30
    assignees:
      - "@Nymphium"
