title: lilyum ensemble
author: Satoru Kawahara
timezone: Asia/Tokyo
description: lily, Aikatsu, Programming language, and more
keywords: lily,百合,Aikatsu,アイカツ,Linux,Lua,MoonScript,言語処理系,プログラム言語
image: pictures/github_icon.png
url: "https://nymphium.github.io"
exclude:
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - _bin
  - slides.rb
  - .sass-cache
  - twicache
  - twicard_cache

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jemoji
  - jekyll-gist
sass:
  style: compressed
markdown: MyCustomProcessor
encoding: "utf-8"
host: 0.0.0.0
