title: lilyum ensemble
author: Satoru Kawahara
timezone: Asia/Tokyo
description: lily, Aikatsu, Programming language, and more
keywords: lily,百合,Aikatsu,アイカツ,Linux,Lua,MoonScript,言語処理系,プログラム言語
image: pictures/github_icon.png
url: "https://nymphium.github.io"
repository: "https://github.com/Nymphium/nymphium.github.io"
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - _bin
  - slides.rb
  - .sass-cache
  - twicache
  - twicard_cache
  - .ruby-lsp
  - .direnv
headersite:
  - slides.html
  - tags.html
  - about/README.md
plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jemoji
  - jekyll-gist
  - jekyll-feed
sass:
  style: compressed
markdown: MyCustomProcessor
issue_repo: nymphium/nymphium.github.io
encoding: "utf-8"
future: true
host: 0.0.0.0
