#!/bin/bash


set -e

filename=${1}
articlename=${2:-${1}}
year=$(date +%Y)
month=$(date +%m)
date=$(date +%d)
postfilename="${year}-${month}-${date}-${filename}"

picdir="pictures"
postdir="_posts"

[ ! "${1}" ] && filename="temp"


mkdir -p "${picdir}/${year}/${month}/${date}/${filename}"

cat <<EOL > "${postdir}/${postfilename}.md"
---
layout: post
title: ${articlename}
tags: []
---
EOL

