#!/usr/bin/bash

set -eu

dir=$(mktemp -d)
message="deploy at $(date)"

bundle install
JEKYLL_ENV=production bundle exec jekyll build
mkdir -p "${dir}"
mv _site/* "${dir}"

git add -A

git commit -m "${message}"
git push origin source:source

: on master branch
: ====
git checkout master
rm -rf $(ls | grep -v .git)
cp -r "${dir}/"* .

git add *
git commit -m "${message}" --allow-empty
git push -f origin master
: ====

git checkout source
git rm -rf "${dir}"

