#!/usr/bin/bash

set -eu

dir=$(mktemp -d)
message="deploy at $(date)"

if [ -e "Gemfile.lock" ]; then
	rm Gemfile.lock
fi

if [ -e "vendor" ]; then
	rm -rf vendor 
fi

bundle install --path vendor
JEKYLL_ENV=production bundle exec jekyll build
mkdir -p "${dir}"
mv _site/* "${dir}"

git add -A

git commit -m "${message}"
wait
git push origin source:source

wait
: on master branch
: ====
git checkout master
rm -rf $(ls -a | grep -v .git)
cp -r "${dir}/"* .
wait

git add -A
git commit -m "${message}" --allow-empty
wait
git push -f origin master
wait
: ====

git checkout source
git rm -rf "${dir}"
git rm -rf vendor
git rm Gemfile.lock

