#!/bin/bash

slide=${1%.*}
slide_uuid="${slide}-$(uuidgen)"
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/default -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${slide_uuid}.pdf" "${slide}.pdf"
mv "${slide_uuid}.pdf" "${slide}.pdf"
pdf-slide-html --pdf-url "http://nymphium.github.io/pdf/${slide}.pdf" --base-url http://azu.github.io/slide-pdf.js/ -o "${slide}.html"
sed -i"" -e 's/\(width="\)100\(%"\)/\190\2/' "${slide}.html"
sed -i"" -e 's/\(height="\)100\(%"\)/\1103\2/' "${slide}.html"

if [[ ! "${2}" = "" ]]; then
	title=$(echo "${2}" | ruby -rcgi -e "puts CGI.escapeHTML ARGF.read")
	sed -i"" -e "s/<title>.\+<\/title>/<title>${title} - lilyum ensemble<\/title>/" "${slide}.html"
else
	title=$(pdfinfo "${slide}.pdf" | awk '$1=="Title:"{print $0}' | sed -e 's/^Title:\s*//' | ruby -rcgi -e "puts CGI.escapeHTML ARGF.read")

	if [[ ! "${title}" = "" ]]; then
		sed -i"" -e "s/<title>.\+<\/title>/<title>${title} - lilyum ensemble<\/title>/" "${slide}.html"
	fi
fi
