#!/bin/bash

slide=${1%.*}
slide_base=$(basename ${slide})
slide_uuid="${slide}-$(uuidgen)"
# gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/default -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${slide_uuid}.pdf" "${slide}.pdf"
# mv "${slide_uuid}.pdf" "${slide}.pdf"
# pdf-slide-html --pdf-url "http://nymphium.github.io/pdf/${slide}.pdf" --base-url http://azu.github.io/slide-pdf.js/ -o "${slide}.html"
# sed -i"" -e 's/\(width="\)100\(%"\)/\190\2/' "${slide}.html"
# sed -i"" -e 's/\(height="\)100\(%"\)/\1103\2/' "${slide}.html"

if [[ ! "${2}" = "" ]]; then
	title=$(echo "${2}" | ruby -rcgi -e "puts CGI.escapeHTML ARGF.read")
	# sed -i"" -e "s/<title>.\+<\/title>/<title>${title} - lilyum ensemble<\/title>/" "${slide}.html"
else
	title=$(pdfinfo "${slide}.pdf" | awk '$1=="Title:"{print $0}' | sed -e 's/^Title:\s*//' | ruby -rcgi -e "puts CGI.escapeHTML ARGF.read")

	# if [[ ! "${title}" = "" ]]; then
		# sed -i"" -e "s/<title>.\+<\/title>/<title>${title} - lilyum ensemble<\/title>/" "${slide}.html"
	# fi
fi

cat <<HTML > pdf/${slide_base}.html
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>${title} - lilyum ensemble</title>
    <style type="text/css">
    .main-content .svg-icon {
        height: 1em;
        vertical-align: text-bottom; }

    html, body, .main-content {
        height: 100%;
        margin: 0 auto;
        padding: 0; }

    #main-slide {
        margin: 0 auto;
        display: block; }

    .slide-controller {
        margin: 0 auto;
        display: block;
        text-align: right; }
    .slide-controller a, .slide-controller p, .slide-controller button {
        vertical-align: text-bottom; }

    .main-content {
        -moz-transform: scale(0.8,0.8);
        -webkit-transform: scale(0.8,0.8);
        -o-transform: scale(0.8,0.8);
        -ms-transform: scale(0.8,0.8);
        width: 90%;
        height: 115%;
        margin-top: -8.5rem;
        padding: 0px;
    }

    .slide-state-fullscreen {
        width: 100%;
        height: 100%; }

    .pdf-canvas {
        width: 85%;
        height: 85%;
    }
    </style>
    <noscript>
        <style>
            .main-content {
                display: none;
            }
        </style>
    </noscript>
</head>
<body>
<div class="main-content">
    <iframe id="main-slide"
            src="https://azu.github.io/slide-pdf.js/?slide=https://nymphium.github.io/pdf/${slide_base}.pdf"
            scrolling="no"
            allowtransparency="true"
            width="90%"
            height="103%"
            style="border:0;">
    </iframe>
    <aside class="slide-controller"><a href="https://nymphium.github.io/pdf/${slide_base}.pdf" title="${title}">
        <svg xmlns="https://www.w3.org/2000/svg"
             version="1.1"
             class="svg-icon"
             viewBox="0 0 512 512">
            <path
                    d="M 224 64 L 224 272 L 128 176 L 128 256 L 256 384 L 384 256 L 384 176 L 288 272 L 288 64 L 224 64 z M 64 320 L 64 448 L 448 448 L 448 320 L 416 320 L 416 416 L 96 416 L 96 320 L 64 320 Z"
                    style="fill:#000000"></path>
        </svg>
        Download PDF</a>
        <button class="fullscreen-button" id="js-fullscreen-button">最大化</button>
    </aside>
</div>
<script>
    (function () {
        // focus slide
        document.getElementById("main-slide").focus();
        var fullScreenButton = document.getElementById("js-fullscreen-button");
        fullScreenButton.addEventListener("click", function () {
            var content = document.querySelector(".main-content");
            content.classList.toggle("slide-state-fullscreen");
        });
    })();
</script>
</body>
</html>
HTML
