#!/bin/bash

# [tweet:twitter-url]
ruby -i -pe 'gsub(/\[tweet:(.*)?\]/) {"<blockquote class=\"twitter-tweet\" lang=\"en\" data-theme=\"dark\"><a href=\"#{$1}\"></a></blockquote><script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"}' "${1}"

# [gh-repo:user/repo]
ruby -i -pe 'gsub(/\[gh-repo:(.*?)\]/) {"<dvi class=\"github-widget\" data-repo=\"#{$1}\"></dvi>"}' "${1}"

# [twid:user]
ruby -i -pe 'gsub(/\[twid:(.+?)\]/) {"[@#{$1}](https://twitter.com/#{$1})"}' "${1}"

