name: "Test"
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          max-jobs = auto
          cores = 0
    - uses: cachix/cachix-action@v15
      with:
        name: blog-ci
        authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Check build
      run: |
        nix develop -c rake build

    - name: Check nix format
      run: |
        nix develop -c nixfmt gemset.nix
        nix develop -c -- nixfmt -c $(git ls-files *.nix)
