name: "Test"
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          max-jobs = auto
          cores = 0

    - uses: cachix/cachix-action@v12
      with:
        name: blog-ci
        authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Check build
      run: |
        nix develop -c bundle install
        nix develop -c bundle exec rake build
