name: "Test"

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - source

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          max-jobs = auto
          cores = 0
    - uses: cachix/cachix-action@v16
      with:
        name: blog-ci
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - name: Check build
      run: |
        nix develop -c rake build

    - name: Check format
      run: |
        nix develop -c -- bash -c 'git ls-files "*.nix" | grep -v gemset.nix | xargs -P0 nixfmt -c'
        nix develop -c actionlint
