name: "Test"

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - source

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          max-jobs = auto
          cores = 0
    - uses: cachix/cachix-action@v16
      with:
        name: blog-ci
        authToken: '${{ secrets.CACHIX_TOKEN }}'

    - uses: actions/cache@v4
      with:
        path: |
          .jekyll-cache
          twicache
          twicard_cache
        key: ${{ runner.os }}-contents-cache


    - name: Check build
      run: |
        nix develop -c rake build

    - name: Check format
      run: |
        nix develop -c -- bash -c 'git ls-files "*.nix" | grep -v gemset.nix | xargs -P0 nixfmt -c'
        nix develop -c actionlint

    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/source'
    needs: tests
    environment:
      name: github-pages
      url: "https://nymphium.github.io"
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
