name: "Test"

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          max-jobs = auto
          cores = 0
    - uses: cachix/cachix-action@v16
      with:
        name: blog-ci
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - name: Check build
      run: |
        nix develop -c rake build

    - name: Check nix format
      run: |
        nix develop -c -- nixfmt -c $(git ls-files *.nix | grep -v gemset.nix)
