name: Run bundix on dependencies-labeled PRs

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: bundix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-on-specific-labels:
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'ruby')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "NEW_BRAHCH=dependabot-update-bundix-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Check for existing branch
        run: |
          if git ls-remote --exit-code --heads origin update-bundix-${{ env.NEW_BRAHCH }}; then
            echo "Branch already exists. Exiting..."
            exit 0
          fi
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v15
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix develop -c bundix
      - uses: peter-evans/create-pull-request@main
        id: create_pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRAHCH }}
          commit-message: 'Update gemset.nix via bundix'
          title: 'Update gemset.nix via bundix'
          body: |
            This PR updates gemset.nix by running `bundix`.
            It is related to the original PR: [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
          base: ${{ github.event.pull_request.head.ref }}
          labels: 'dependencies,bundix'
      - name: Add comment to original PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            A new PR has been created to update gemset: [${{ steps.create_pr.outputs.pull-request-url }}](${{ steps.create_pr.outputs.pull-request-url }})
          pr-number: ${{ github.event.pull_request.number }}
