name: Run bundix on dependencies-labeled PRs

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: bundix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-on-specific-labels:
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'ruby')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "NEW_BRAHCH=dependabot-update-bundix-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Check for existing branch
        run: |
          if git ls-remote --exit-code --heads origin update-bundix-${{ env.NEW_BRAHCH }}; then
            echo "Branch already exists. Exiting..."
            exit 0
          fi
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v15
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b ${{ env.NEW_BRAHCH }}
      - run: nix develop -c bundix
      - run: |
          git add gemset.nix
          git commit -m "Update gemset.nix via bundix"
      - run: git push origin ${{ env.NEW_BRAHCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRAHCH }}
          title: 'Update gemset.nix via bundix'
          body: 'This PR updates gemset.nix by running bundix.'
          base: ${{ github.event.pull_request.base.ref }}
          labels: 'dependencies,bundix'
