name: Run bundix on dependencies-labeled PRs

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write

jobs:
  run-on-specific-labels:
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'ruby')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v15
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix develop -c bundix
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --all -m "Update gemset.nix via bundix" || echo "No changes to commit"
          git push origin --force-with-lease ${{ github.event.pull_request.head.ref }}:refs/heads/${{ github.event.pull_request.head.ref }}
