name: Run bundix on dependencies-labeled PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  followup-bundix:
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      head_ref: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.head_ref }}
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v16
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix run '.#patched-bundix'
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Update gemset.nix via bundix'
