name: Run bundix on dependencies-labeled PRs

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  followup-bundix:
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'ruby') &&
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v15
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix run '.#patched-bundix'
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --all -m "Update gemset.nix via bundix" || echo "No changes to commit"
          git fetch origin
          git rebase origin/${{ github.event.pull_request.head.ref }} || git merge origin/${{ github.event.pull_request.head.ref }}
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" ${{ github.event.pull_request.head.ref }}:refs/heads/${{ github.event.pull_request.head.ref }}
