name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 1 * *' # runs every monyh 1st

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = auto
            cores = 0
      - uses: cachix/cachix-action@v15
        with:
          name: blog-ci
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
      - name: Check build
        run: |
          nix develop -c nixfmt gemset.nix
          nix develop -c rake build
          git diff --exit-code
